scan:
  scanners:
    - secret
    - misconfig

ignorefile: .github/trivy/.trivyignore.yml

severity:
  - HIGH
  - CRITICAL

misconfiguration:
  scanners:
    - terraform
  config:
    terraform:
      file_patterns:
        - "**/*.tf"
  ignore_unfixed: true
